FROM aarch64/alpine:latest
ENV ARCH=arm64
RUN apk --no-cache --update add curl mosquitto-clients jq bc
COPY *.sh /
COPY *.pem /
RUN mkdir -p devenv
COPY devenv/*.pem /devenv/
WORKDIR /
CMD /workload.sh
