FROM armhf/alpine:latest
ENV ARCH=armhf
RUN apk --no-cache --update add curl mosquitto-clients jq bc
COPY *.sh /
COPY *.pem /
#RUN mkdir -p devenv
#COPY devenv/*.pem /devenv/
WORKDIR /
CMD /workload.sh
