FROM golang:1.10.0-alpine as build
COPY main.go /
ARG version=0.0.1
ENV MIC_VERSION $version
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo --ldflags "-X main.version=${MIC_VERSION}" -o /bin/microphone /main.go

FROM alpine:latest
RUN apk --no-cache add alsa-utils
COPY --from=build /bin/microphone /bin/microphone
WORKDIR /
CMD ["/bin/microphone"]
