FROM arm32v6/python:3-alpine

RUN apk --no-cache --update add mosquitto-clients

# Install flask (for the REST API server)
RUN pip install Flask

# Copy the dummy images
COPY *.jpg /

# Copy over the source
COPY monitor.py /
WORKDIR /

# Run the daemon
CMD python monitor.py
