FROM ubuntu:bionic

RUN apt-get update
RUN apt-get install -y alsa
RUN apt-get install -y alsa-utils mosquitto mosquitto-clients \ 
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /
COPY voice2audio.sh /
CMD ./voice2audio.sh
