FROM ubuntu:bionic

RUN apt-get update && apt-get install -q -y --no-install-recommends \
  socat \
  curl \
  jq \
  fswebcam

COPY mock.jpg /
COPY start.sh /
COPY cam.sh /
WORKDIR /
CMD ["./start.sh"]

