#!/bin/sh

./server -b ${MQTT_BROKER} -u ${MQTT_SERVER_USER} -p ${MQTT_SERVER_PASS} -c ${MQTT_SERVER_CLIENT} -r ${SAMPLE_RATE} --result_topic ${MQTT_RESULTS_TOPIC} -l ${LOG_LEVEL} -n ${NFFT} -i ${PEAKS_LIMIT} -e ${PEAKS_THRESHOLD} -f ${FREQS_THRESHOLD} -q ${MQTT_QOS}