FROM armhf/alpine:latest
MAINTAINER Chris Dye <dyec@us.ibm.com>

ENV ARCH=armhf

# Need to do this on a single line so this docker image layer will have the pkgs removed
#RUN apk add --no-cache build-base; apk del build-base
RUN apk --no-cache update && apk --no-cache add python python-dev py-pip && pip install --upgrade pip paho-mqtt && apk del python-dev py-pip

COPY *.py /
COPY *.pem /

WORKDIR /

CMD python netspeed_edge.py --verbose --mqtt --policy
