FROM alpine:latest

RUN apk update \
    && apk add --no-cache bash mosquitto mosquitto-clients \
    && rm -fr /tmp/*

COPY test_mqtt.sh /
WORKDIR /
RUN ["chmod", "+x", "./mqtt.sh"]
CMD ["./mqtt.sh"]