#!/bin/bash
# Read from stdin a config file that has simple variable=value lines and transform it into
# a file that can be included in a makefile, and write that to stdout.

# The sed -e flags does these things (in this order):
# - remove any export lines
# - delete comment lines
# - remove blank lines
# - remove single quotes
# - remove double quotes
# - add "export " to the beginning of each line

sed -e '/^export /d' -e '/^ *#/d' -e '/^ *$/d' -e "s/'//g" -e 's/"//g' -e 's/^/export /'
